name: Python test

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # You can specify the exact version you need here
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest test_folder/test_main.py test_folder/check_add.py  # You can add more test files here
