name: pytest-coverage-comment
on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'
    
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
      - name: Generate Coverage Report for text  
        run: |  
          coverage report -m >pytest-coverage-tx.txt

      - name: Generate Coverage Report for xml  
        run: |  
          coverage report -m >pytest-coverage-xm.xml


          
# name: pytest with coverage

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     name: Run pytest with coverage
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
      
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pytest pytest-cov

#       - name: Run tests with coverage
#         run: |
#           pytest --cov=./

#       - name: Upload coverage report
#         uses: actions/upload-artifact@v2
#         with:
#           name: coverage-report
#           path: coverage.xml
