name: Pytest with Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pytest pytest-cov

    - name: Run tests with coverage
      run: pytest --cov=test_folder test_folder/

    - name: Generate coverage report
      run: |
        coverage html
        mv htmlcov coverage_report
      if: always()

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage_report
