# .github/workflows/pytest.yml

name: Pytest with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov
        pip install -e main_code  # Install your main code as editable (assuming it's a package)

    - name: Run pytest with coverage
      run: pytest --cov=main_code test_folder/

    - name: Generate coverage report
      run: |
        coverage html
        mv htmlcov coverage_report
      if: always()

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage_report
