name: pytest-coverage-comment
on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s

      - name: Generate Coverage Report
        run: |
          coverage report -m

      - name: Generate Coverage Report for text
        run: |
          coverage report -m > pytest-coverage-tx.txt

      - name: Generate Coverage Report for xml
        run: |
          coverage xml -o pytest-coverage-xm.xml

      - name: Upload Coverage Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            pytest-coverage-tx.txt
            pytest-coverage-xm.xml

      # - name: Log in to Docker Hub
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #   run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # - name: Build Docker image
      #   run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/vini:latest

      # - name: Push Docker image to Docker Hub
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/vini:latest

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: nanajanashia/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
