# name: pytest-coverage-comment
# on:
#   push:
#     branches:
#       - '*' 
#   pull_request:
#     branches:
#       - '*'
    
  
# jobs:  
#   build:  
#     runs-on: ubuntu-latest  
#     strategy:  
#       matrix:  
#         python-version: ["3.10"]  
  
#     steps:  
#       - uses: actions/checkout@v3  
#       - name: Set up Python ${{ matrix.python-version }}  
#         uses: actions/setup-python@v4  
#         with:  
#           python-version: ${{ matrix.python-version }}  
#       - name: Install dependencies  
#         run: |  
#           python -m pip install --upgrade pip  
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
#       - name: Test with pytest  
#         run: |  
#           coverage run -m pytest  -v -s  
#       - name: Generate Coverage Report  
#         run: |  
#           coverage report -m
#       - name: Generate Coverage Report for text  
#         run: |  
#           coverage report -m >pytest-coverage-tx.txt

#       - name: Generate Coverage Report for xml  
#         run: |  
#           coverage report -m >pytest-coverage-xm.xml

# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment
on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          
