name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
      - name: Generate pytest-coverage.txt
        run: |
          # Run pytest with coverage and save the report to pytest-coverage.txt
          coverage run -m pytest --cov=. --cov-report=xml:pytest-coverage.xml
          # Convert coverage XML report to text format
          coverage xml -o pytest-coverage.txt
      - name: Generate pytest.xml
        run: |
          # Run pytest and save the report to pytest.xml
          pytest --junitxml=pytest.xml
      - name: Test with pytest
        run: |
          coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
